

- name: Create /tmp/gcrimages directory
  file: path=/tmp/gcrimages state=directory mode=0755


- name: Copy images to node
  copy:
    src: "{{ item }}"
    dest: "/tmp/gcrimages/{{ item }}"
    mode: 0644
  with_items:
    - gcr.pause.tar


- name: Load images
  shell: "docker load -i /tmp/gcrimages/{{ item }}"
  with_items:
    - gcr.pause.tar

